name: single_instance_xx
description: Forces a single instance of your Windows app, bringing the existing window to the front when a new instance is opened.
version: 2.0.0
homepage: https://github.com/SongbookPro/flutter_windows_single_instance

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

  win32: ">=2.5.0 <6.0.0"
  ffi: ">=1.0.0 <3.0.0"
  args: ^2.4.2
  path: ^1.9.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: SingleInstanceXxPlugin
